# 关于Promise
使用Promise的时候有几点需要注意的

1. Promise构造函数接收的函数作为参数，这个函数是立即运行的，同时调用resolve或reject并不会阻止参数函数的运行
```javascript
const p = new Promise(function(resolve, reject) {
  console.log('a')
  resolve()
  console.log('b')
})
p.then(function(resolve, reject) {
  console.log('c')
})
console.log('d')

// 运行结果
// a b d c
```

2. resolve函数的参数除了可以是正常的值以外，也可以是一个Promise实例
```javascript
const p1 = new Promise(function (resolve, reject) {
  // ...
})

const p2 = new Promise(function (resolve, reject) {
  // ...
  resolve(p1)
})
```
p2此时会等待p1的状态变更，当p1变成resolve或者reject时，p2的回调函数才会立即执行，根据p1的状态决定p2是then还是reject
```javascript
const p1 = new Promise(function (resolve, reject) {
  setTimeout(() => reject(new Error('fail')), 3000)
})

const p2 = new Promise(function (resolve, reject) {
  setTimeout(() => resolve(p1), 1000)
})

p2
  .then(result => console.log(result))
  .catch(error => console.log(error))
// Error: fair
```
p2在1s的时候本来可以变更状态，但是由于resolve的参数是一个promise，则转变成等待该promise状态改变。  
3s后p1的状态变成rejected，所以p2也变成rejected

3. catch可以是reject函数被调用，也可以是内部抛出异常
```javascript
const p = new Promise((resolve, reject) => {
  throw new Error('this is an error')
})
p.catch(err => console.log(err))
// Error: this is an error
```

4. Promise的状态一旦改变便无法改变
```javascript
const promise = new Promise(function(resolve, reject) {
  resolve('ok')
  throw new Error('test')
})
promise
  .then(function(value) { console.log(value) })
  .catch(function(error) { console.log(error) })
// ok
```
由于promise已经将状态变为resolved，所以即使后续抛出异常test也是无效的。

5. Promise.resolve和Promise.reject
## Promise.resolve
Promise.resolve可以接收一个基本的值作为参数，也可以接收一个promise为参数，甚至可以接收一个thenable的对象
```javascript
Promise.resolve('done')

Promise.resolve(fs.readFile())

const obj = {
  then() {
    console.log('done')
    return 'done'
  }
}
Promise.resolve(obj) // done
```
当一个对象具备then方法，我们称之为thenable对象，当传入Promise.resolve时，会被立即执行then方法。

Promise.resolve()会返回promise对象，并且是在本轮“事件循环”的结束时，而不是下一轮“事件循环”的开始时
```javascript
setTimeout(() => {
  conmsole.log('tree')
}, 0)

Promise.resolve().then(() => console.log('two'))

console.log('one')

// one
// two
// three
```
由于setTimeout是在下一轮“事件循环”开始时执行，而Promise.resolve是在本轮“事件循环”结束时执行。

# Promise.reject
Promise.reject的参数只能被当做错误返回，即使它是个具备then方法的对象
```javascript
const thenable = {
  then() {
    console.log('done')
  }
}
const p = Promise.reject()
p.catch(err => {
  console.log(err.then === thenable)
})
```

# Timer
* setTimeout()
* setInterval()
* setImmediate()
* process.nextTick()

考虑如下代码
```javascript
setTimeout(() => console.log(1));  // ①
setImmediate(() => console.log(2)); // ②
process.nextTick(() => console.log(3)); // ③
Promise.resolve().then(() => console.log(4)); // ④
(() => console.log(5))(); // ⑤
```
运行结果
```
5
3
4
1
2
```

其中⑤先打印输出5毫无疑问，因为是同步的代码，执行到就直接输出了。

然后看异步的操作，异步循环分两种：
1. 追加在本轮循环的异步
2. 追加在次轮循环的异步

其中`process.nextTick`和`Promise`的回调函数，追加在本轮循环，即同步任务一旦执行完，就开始执行他们。  
而`setTimeout`、`setInterval`和`setImmediate`的回调函数，将在次轮循环中执行

因此上述代码③和④将会比①和②先执行。

当开始执行本轮循环的异步任务时，会先执行`process.nextTick`，它是所有异步任务里最快被执行的，因此③先被执行，④后被执行。  
此时执行顺序为⑤③④

## 异步循环阶段分析
当进入次轮循环，主线程会不断进行事件循环，每轮循环分成如下6个阶段

### 什么是事件循环（event loop）
虽然node.js是单线程的，但是事件循环（event loop）让node.js拥有了非阻塞异步io的功能，主要就是将一些操作尽可能的挪到了操作系统来执行。

而当前很多系统的内核都是多线程的，它们可以处理处理的更多的操作。当其中一个线程完成了操作，内核就会通知node.js，相应的回调就会被加入到 **轮询队列（poll queue）** 中，并最终得到执行。

### 事件循环（event loop）的解释
当node.js启动后，它便会初始化事件循环，开始处理提供的脚本，这些脚本有可能是异步的API调用，定时任务或者是process.nextTick()，之后开始进行事件循环。

```
   ┌───────────────────────┐
┌─>│        timers         │
│  └──────────┬────────────┘
│  ┌──────────┴────────────┐
│  │    pending callbacks  │
│  └──────────┬────────────┘
│  ┌──────────┴────────────┐
│  │     idle, prepare     │
│  └──────────┬────────────┘      ┌───────────────┐
│  ┌──────────┴────────────┐      │   incoming:   │
│  │         poll          │<─────┤  connections, │
│  └──────────┬────────────┘      │   data, etc.  │
│  ┌──────────┴────────────┐      └───────────────┘
│  │        check          │
│  └──────────┬────────────┘
│  ┌──────────┴────────────┐
└──┤    close callbacks    │
   └───────────────────────┘
```
每个阶段都有一个由回调函数组成的先入先出的队列（FIFO queue）。虽然每个阶段都以自己的方式特殊，通常地，当事件循环进入到某个阶段，会执行该阶段特有的操作，然后会执行该阶段队列中的回调函数，直到队列为空（exhausted）或者达到可执行回调个数的最大值。当队列为空或者达到可执行回调最大值，事件循环会进入下一个阶段，如此往复。

由于这些操作会产生出更多的操作，并且轮询阶段处理的新事件会被加入到内核的队列，轮询事件被处理的时候会有新的轮询事件加入。于是，长时回调任务会导致轮询阶段的时间超过了定时器的阈值。具体可见下方对定时器（timers）和轮询（poll）描述部分。

### 事件循环（event loop）的各个阶段
1. **timers阶段**，本阶段执行setTimeout() 和 setInterval() 计划的回调。
2. **pending callback阶段**，执行延迟到下一个循环迭代的I/O回调。
3. **idle,prepare阶段**，是libuv内部的调用。
4. **poll阶段**，获取新的I/O事件，执行IO相关的回调。nodejs这时会适当进行阻塞；
5. **check阶段**，该阶段setImmediate的回调函数会被调用
6. **close callbacks阶段**，一些关闭事件的回调会被调用，如`socket.on('close', ...)`

在事件循环运行之间，Node.js检查是否有正在等待的异步I/O或者定时器，如果没有就会干净的退出。

### 阶段的详细细节
#### timers
定时器的作用就是让某个回调在达到指定的阈值后执行。timers的回调callback会在指定的时间后尽快的执行。然而，操作系统的计划或者其他回调的执行可能会延迟该回调的执行。另外，poll阶段也会影响到timers的执行时机。

这里有个案例，定时器setTimeout会在100毫秒后执行回调函数，然后假设你还有个异步的耗费95毫秒的读文件操作。
```javascript
const fs = require('fs');

function someAsyncOperation(callback) {
  // Assume this takes 95ms to complete
  fs.readFile('/path/to/file', callback);
}

const timeoutScheduled = Date.now();

setTimeout(() => {
  const delay = Date.now() - timeoutScheduled;

  console.log(`${delay}ms have passed since I was scheduled`);
}, 100);


// do someAsyncOperation which takes 95 ms to complete
someAsyncOperation(() => {
  const startCallback = Date.now();

  // do something that will take 10ms...
  while (Date.now() - startCallback < 10) {
    // do nothing
  }
});
```
这里事件循环进入到poll阶段后，它的队列是空的（因为fs.readFile()还没有完成），所以它会继续的等待，直到达到最快的定时器的阈值。当它等待到95ms时，`fs.raedFile()`完成文件读取，它的回调函数会被加入到poll队列中，这个回调函数需要耗费10ms的执行时间。当回调执行结束，poll队列中已经没有其他回调可执行，这时事件循环会检查是否有到达阈值的定时器，然后回到timers阶段来执行该定时器的回调函数。在这个案例中，你会看到这个定时器回调函数是在105ms后执行的。

**注意：** 为了避免poll阶段将事件循环饿死，libuv根据操作系统的不同设置一个轮询的上限值。

#### pending callbacks
该阶段会执行一些诸如tcp错误之类的操作系统的回调。例如，如果一个TCP socket在尝试连接时收到了ECONNREFUSED错误，某些 *nix系统会等着报告这个错误。这个就会被排到本阶段的队列中。

#### poll
这几个阶段中，大部分都好理解，其中poll阶段会比较复杂，也是衔接整个event loop中较为重要的阶段。  
在node.js里，任何异步方法（除timer,close,setImmediate之外）完成时，都会将其callback加到poll queue里,并立即执行。

poll阶段主要有两个功能：
1. 计算它应该阻塞和轮询I/O的时间
2. 处理poll队列（poll queue）的回调（callbacks）

当事件循环进入poll阶段，且没有定时器被设定，将会发生如下情况：
* 如果poll队列不为空，事件循环将轮询poll队列，然后同步的执行queue里的回调函数，直到队列为空或者达到指定的回调执行次数。
* 如果poll队列为空，将会发生下面情况：
    * 如果有setImmediate设定了回调，将结束poll阶段进入check阶段，并执行check阶段的queue
    * 如果没有设定setImmediate回调，事件循环将阻塞在该阶段等待回调加入poll队列，然后立即执行。

一旦poll队列为空，事件循环会去检查是否有到期的定时器。如果有一个或者更多的定时器回调准备执行，事件循环会回到timers阶段执行那些定时器的回调函数。

#### check
在poll阶段结束之后，该阶段会立马执行回调。如果poll阶段变得空闲，而且通过setImmediate将回调入队，事件循环会进入check阶段而不是在poll阶段等待。

`setImmediate()`是个特殊的定时器，在事件循环中一个单独的阶段运行。它使用libuv的API来使得回调函数在poll阶段完成后执行。

基本上，随着代码的执行，事件循环会最终进入到等待状态的poll阶段（poll队列已经为空），可能是等待一个连接、请求等。然而，如果有一个setImmediate()设置了一个回调并且poll阶段空闲了，那么事件循环会进入到check阶段而不是等待poll事件。

#### close callbacks
如果一个socket或句柄（handle）被突然关闭，例如`socket.destroy()`，然后`'close'`事件会在这个阶段被触发。除此之外，它还会通过`process.nextTick()`被触发。

### 总结
现在我们知道，setImmediate在check阶段才会被执行，在timer之后，因此大部分情况下都会慢于timer的相关函数，因此之前的例子先执行①再执行②，最终结果为⑤③④①②。

### 再说setTimeout和setImmediate
这两个很相似，但调用时机会的不同会导致它们不同的表现。
* setImmediate() 被设计成一旦轮询阶段完成就执行回调函数；
* setTimeout() 规划了在某个时间值过后执行回调函数；

这两个执行的顺序会依赖于调用它们的上下文。如果他们都是在同一个模块中被调用，这时计时器就会受到进程性能的影响（运行在本机的其他程序会影响它们）。

例如下面的例子，下面的代码运行在没有IO操作的模块当中，两个定时器的执行顺序是无法确定的，它们会受绑定它们的进程的性能影响。
```javascript
// timeout_vs_immediate.js
setTimeout(() => {
  console.log('timeout');
}, 0);

setImmediate(() => {
  console.log('immediate');
});
```
```
$ node timeout_vs_immediate.js
timeout
immediate

$ node timeout_vs_immediate.js
immediate
timeout
```
然而如果我们将他们移到IO操作的模块当中，那么setImmediate的回调总是会被优先执行。
```javascript
// timeout_vs_immediate.js
const fs = require('fs');

fs.readFile(__filename, () => {
  setTimeout(() => {
    console.log('timeout');
  }, 0);
  setImmediate(() => {
    console.log('immediate');
  });
});
```
```
$ node timeout_vs_immediate.js
immediate
timeout

$ node timeout_vs_immediate.js
immediate
timeout
```
setImmediate()比setTimeout()优势的地方是 setImmediate()在 I/O循环中总是先于任何定时器，不管已经定义了多少定时器。

# 补充一下
我们已经知道process.nextTick并不属于事件循环的一部分，它会在代码块结束运行后，在事件循环开始前执行。

因此如果在process.nextTick回调函数里有很耗cpu的操作，也就等同于阻塞了事件循环的开始了。

既然如此为什么还要提供这样的api呢，被设计出来必然有它的原因。

```javascript
let bar;

function someAsyncApiCall(callback) { callback() }
someAsyncApiCall(() => {
  console.log('bar', bar); // undefined
})

bar = 1
```
代码打印出了bar为undefined，因为我们的callback是个同步操作，执行的时候bar并未赋值。

改变一下：
```javascript
let bar;

function someAsyncApiCall(callback) {
  process.nextTick(callback);
}

someAsyncApiCall(() => {
  console.log('bar', bar); // 1
});

bar = 1;
```
此时打印出bar为1，因为nextTick是在本轮代码执行结束后执行，此时bar已经有值了。

看一个我们日常使用的代码
```javascript
const server = net.createServer(() => {}).listen(8080)

server.on('listening', () => {})
```
根据node文档，listening事件的回调函数会在listen()方法被调用时马上触发执行，假设listen的代码如下：
```javascript
Server.prototype.listen = function (port) {
  // some code
  this.emit('listening')
}
```
由于在调用listen时`server.on('listening', () => {})`的代码还未被执行，因此回调函数无法被调用。我们改下代码
```javascript
Server.prototype.listen = function (port) {
  // some code
  process.nextTick(() => {
    this.emit('listening')
  })
}
```
这时listening事件的回调函数就可以被执行了，因为触发listening时，`server.on('listening', () => {})`已经执行了。

由上述例子我们也能知道方法emit是同步的，它会调用所有已经被注册的事件。

因此如果我们希望有些代码是在代码块执行结束之后立马被执行的，便可以使用process.nextTick
